# Copyright (c) 2025 Affilibuster by Ronen Druker.

"""
SQLAlchemy model for Strapi API Tokens.

Maps to the strapi_api_tokens table in the database.
Used to read the auto-generated API token for backend authentication.
"""

from datetime import UTC, datetime

from sqlalchemy import DateTime, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from affilibuster_backend.infrastructure.database.models import Base


class StrapiApiTokenModel(Base):
    """
    SQLAlchemy model for strapi_api_tokens table.

    Stores API tokens generated by Strapi.
    The backend reads the 'Full Access' token from here to authenticate with Strapi.
    """

    __tablename__ = "strapi_api_tokens"

    # Primary Key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Token Name
    name: Mapped[str] = mapped_column(String(255), nullable=False)

    # Token Description
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Token Type (e.g., 'full-access', 'read-only')
    type: Mapped[str] = mapped_column(String(255), nullable=False)

    # Access Key (The actual token used for authentication)
    access_key: Mapped[str] = mapped_column(String(255), nullable=False)

    # Audit Fields
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(UTC),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
    )
    expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    last_used_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    def __repr__(self) -> str:
        """String representation of StrapiApiToken."""
        return f"<StrapiApiToken(name='{self.name}', type='{self.type}')>"
