# Copyright (c) 2025 Affilibuster by Ronen Druker.

"""
Unit tests for main application module.

Tests cover startup functions, middleware, and utility endpoints.
"""

from unittest.mock import AsyncMock, Mock, patch

import pytest
from fastapi import FastAPI, HTTPException
from starlette.requests import Request

from affilibuster_backend.domain.entities.generated.models import HealthResponse, RootResponse
from affilibuster_backend.main import APIVersionMiddleware, app, health, http_exception_handler, lifespan, root


@pytest.mark.asyncio
class TestCustomOpenAPI:
    """Test suite for custom_openapi function."""

    async def test_custom_openapi_returns_cached_schema(self):
        """Test custom_openapi returns cached schema when available."""
        # Arrange
        cached_schema = {"openapi": "3.0.0", "info": {"title": "Cached"}}
        with patch.object(app, "openapi_schema", cached_schema):
            # Act
            result = app.openapi()

            # Assert
            assert result == cached_schema

    async def test_custom_openapi_uses_contract_spec_when_available(self):
        """Test custom_openapi uses contract specification when available."""
        # Arrange
        contract_spec = {"openapi": "3.0.0", "info": {"title": "Contract"}}

        with patch.object(app, "openapi_schema", None):
            with patch("affilibuster_backend.main.openapi_contract_loader") as mock_loader:
                mock_loader.get_spec.return_value = contract_spec

                # Act
                result = app.openapi()

                # Assert
                assert result == contract_spec
                assert app.openapi_schema == contract_spec

    async def test_custom_openapi_falls_back_to_autogenerated(self):
        """Test custom_openapi falls back to auto-generated schema when contract unavailable."""
        # Arrange
        with patch.object(app, "openapi_schema", None):
            with patch("affilibuster_backend.main.openapi_contract_loader") as mock_loader:
                with patch("affilibuster_backend.main.get_openapi") as mock_get_openapi:
                    mock_loader.get_spec.return_value = None
                    mock_get_openapi.return_value = {"openapi": "3.0.0", "info": {"title": "Auto"}}

                    # Act
                    result = app.openapi()

                    # Assert
                    assert result == {"openapi": "3.0.0", "info": {"title": "Auto"}}
                    mock_get_openapi.assert_called_once()


@pytest.mark.asyncio
class TestHTTPExceptionHandler:
    """Test suite for http_exception_handler."""

    async def test_http_exception_handler_returns_dict_detail(self):
        """Test handler returns dict detail directly without wrapper."""
        # Arrange
        request = Mock(spec=Request)
        exc = HTTPException(
            status_code=400,
            detail={"error": "validation_error", "message": "Invalid input"},
        )

        # Act
        response = await http_exception_handler(request, exc)

        # Assert
        assert response.status_code == 400
        assert response.body == b'{"error":"validation_error","message":"Invalid input"}'

    async def test_http_exception_handler_wraps_string_detail(self):
        """Test handler wraps string detail in standard format."""
        # Arrange
        request = Mock(spec=Request)
        exc = HTTPException(status_code=404, detail="Not found")

        # Act
        response = await http_exception_handler(request, exc)

        # Assert
        assert response.status_code == 404
        assert response.body == b'{"detail":"Not found"}'


@pytest.mark.asyncio
class TestAPIVersionMiddleware:
    """Test suite for APIVersionMiddleware."""

    async def test_api_version_middleware_adds_header(self):
        """Test middleware adds X-API-Version header to response."""
        # Arrange
        middleware = APIVersionMiddleware(app)
        request = Mock(spec=Request)

        # Mock call_next to return a response
        mock_response = Mock()
        mock_response.headers = {}
        call_next = AsyncMock(return_value=mock_response)

        # Act
        result = await middleware.dispatch(request, call_next)

        # Assert
        assert result.headers["X-API-Version"] == "1.0.0"
        call_next.assert_called_once_with(request)


@pytest.mark.asyncio
class TestRootEndpoint:
    """Test suite for root endpoint."""

    async def test_root_returns_api_info(self):
        """Test root endpoint returns API information."""
        # Act
        result = await root()

        # Assert - validate against autogenerated model
        assert isinstance(result, RootResponse)
        assert result.message == "Affilibuster API v1.0.0"
        assert result.status == "running"


@pytest.mark.asyncio
class TestHealthEndpoint:
    """Test suite for health check endpoint."""

    async def test_health_returns_healthy_status(self):
        """Test health endpoint returns healthy status."""
        # Act
        result = await health()

        # Assert - validate against autogenerated model
        assert isinstance(result, HealthResponse)
        assert result.status == "healthy"


@pytest.mark.asyncio
class TestLifespan:
    """Test suite for application lifespan handler."""

    async def test_lifespan_initializes_dependencies_on_startup(self):
        """Test lifespan initializes dependencies during startup."""
        # Arrange
        mock_app = Mock(spec=FastAPI)

        with patch("affilibuster_backend.main.initialize_dependencies") as mock_init:
            # Act
            async with lifespan(mock_app):
                # Assert - initialization called during startup
                mock_init.assert_called_once()

    async def test_lifespan_completes_shutdown_successfully(self):
        """Test lifespan completes shutdown phase successfully."""
        # Arrange
        mock_app = Mock(spec=FastAPI)

        with patch("affilibuster_backend.main.initialize_dependencies"):
            # Act & Assert - should not raise any exceptions
            async with lifespan(mock_app):
                pass  # Startup phase
            # Shutdown phase completes here
