# Copyright (c) 2025 Affilibuster by Ronen Druker.

"""
API Configuration repository implementation using SQLAlchemy.

Provides access to shared configuration stored in the api_config table.
Primary use case: Reading Strapi API token generated by CMS during bootstrap.
"""

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from affilibuster_backend.infrastructure.database.models.api_config import ApiConfigModel


class ConfigRepository:
    """PostgreSQL implementation for accessing api_config table."""

    def __init__(self, session: AsyncSession) -> None:
        """
        Initialize repository with SQLAlchemy session.

        Args:
            session: SQLAlchemy async session for database operations

        """
        self.session = session

    async def get_value(self, key: str) -> str | None:
        """
        Get configuration value by key.

        Args:
            key: Configuration key to look up

        Returns:
            Configuration value if found, None otherwise

        """
        stmt = select(ApiConfigModel.value).where(ApiConfigModel.key == key)
        result = await self.session.execute(stmt)
        return result.scalar_one_or_none()

    async def get_config(self, key: str) -> ApiConfigModel | None:
        """
        Get full configuration record by key.

        Args:
            key: Configuration key to look up

        Returns:
            ApiConfigModel instance if found, None otherwise

        """
        stmt = select(ApiConfigModel).where(ApiConfigModel.key == key)
        result = await self.session.execute(stmt)
        return result.scalar_one_or_none()
