# Copyright (c) 2025 Affilibuster by Ronen Druker.

"""
Test helper utilities for integration tests.

Provides utilities for comparing test data while excluding Strapi system fields.
"""

from typing import Any

from pydantic import BaseModel

# Strapi system fields to exclude from test comparisons
STRAPI_SYSTEM_FIELDS = {
    "documentId",
    "id",
    "createdAt",
    "updatedAt",
    "publishedAt",
    "locale",
    "localizations",
}


def exclude_system_fields(
    data: dict[str, Any] | BaseModel, additional_fields: set[str] | None = None
) -> dict[str, Any]:
    """
    Remove Strapi system fields from data for test assertions.

    System fields (documentId, id, createdAt, updatedAt, publishedAt,
    locale, localizations) are auto-generated by Strapi and should not
    be compared in tests.

    Args:
        data: Pydantic model or dict to filter
        additional_fields: Optional additional field names to exclude

    Returns:
        Dict with system fields removed

    Example:
        >>> from tests.fixtures.expected_seed_data import EXPECTED_CURRENCIES
        >>> expected = next(c for c in EXPECTED_CURRENCIES if c.code == "USD")
        >>> filtered = exclude_system_fields(expected)
        >>> # filtered: {"code": "USD", "name": "US Dollar", ...}
        >>> # (no documentId, id, timestamps)

    """
    # Convert Pydantic model to dict if needed
    data_dict = data.model_dump() if isinstance(data, BaseModel) else data.copy()

    # Combine system fields with any additional exclusions
    fields_to_exclude = STRAPI_SYSTEM_FIELDS.copy()
    if additional_fields:
        fields_to_exclude.update(additional_fields)

    # Remove system fields
    return {k: v for k, v in data_dict.items() if k not in fields_to_exclude}


def assert_strapi_data_matches(
    actual: dict[str, Any],
    expected: dict[str, Any] | BaseModel,
    ignore_fields: set[str] | None = None,
) -> None:
    """
    Assert that actual Strapi response matches expected data, ignoring system fields.

    Filters out system fields and compares content fields only.
    Provides clear error message on mismatch.

    Args:
        actual: Dict from API response
        expected: Expected data (Pydantic model or dict)
        ignore_fields: Optional additional fields to ignore beyond system fields

    Raises:
        AssertionError: If filtered data doesn't match

    Example:
        >>> actual_usd = response.json()["data"][0]
        >>> expected_usd = EXPECTED_CURRENCIES[0]
        >>> assert_strapi_data_matches(actual_usd, expected_usd)

    """
    actual_filtered = exclude_system_fields(actual, ignore_fields)
    expected_filtered = exclude_system_fields(expected, ignore_fields)

    assert actual_filtered == expected_filtered, (
        f"Strapi data mismatch:\nActual:   {actual_filtered}\nExpected: {expected_filtered}"
    )
