#!/usr/bin/env bash
# Copyright (c) 2026 Affilibuster by Ronen Druker.
#
# Generate Production Environment Configuration
# ==============================================
#
# This script creates a .env.prod file with:
#   - Auto-generated secrets (random base64 values)
#   - Static values for Docker hostnames and URLs
#   - Interactive prompts for external service credentials
#
# Usage:
#   Run from the affilibuster repo root:
#     bash scripts/generate-env-prod.sh
#
# Output:
#   Creates .env.prod in the current directory

# Show help message
show_help() {
  cat <<'HELP'
Usage: generate-env-prod.sh [OPTIONS]

Generate production environment configuration (.env.prod) for Affilibuster VPS deployment.

OPTIONS:
  -h, --help     Show this help message and exit

DESCRIPTION:
  This script creates a .env.prod file with:
    - Auto-generated secrets (Postgres password, JWT keys, API tokens)
    - Static Docker hostnames and production URLs
    - Interactive prompts for Cloudinary credentials

  Run this script from the affilibuster repository root on your production VPS.

EXAMPLES:
  # Generate .env.prod interactively
  ./scripts/generate-env-prod.sh

  # Show help
  ./scripts/generate-env-prod.sh --help

NOTES:
  - The generated .env.prod file contains sensitive secrets
  - Never commit .env.prod to version control
  - Back up your .env.prod securely

HELP
  exit 0
}

# Parse arguments
for arg in "$@"; do
  case "${arg}" in
  -h | --help)
    show_help
    ;;
  *)
    # Ignore other arguments
    ;;
  esac
done

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Logging functions (output to stderr so they don't interfere with function returns)
log_info() { echo -e "${BLUE}[INFO]${NC} $1" >&2; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1" >&2; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1" >&2; }
log_prompt() { echo -e -n "${CYAN}[INPUT]${NC} $1 " >&2; }

# Generate a random base64 secret
generate_secret() {
  openssl rand -base64 32 | tr -d '\n'
}

# Generate a shorter password (for Postgres)
generate_password() {
  openssl rand -base64 24 | tr -d '\n'
}

# Prompt for a required value (reads from /dev/tty to work in subshells)
prompt_required() {
  local prompt_text="$1"
  local value=""

  while [[ -z "${value}" ]]; do
    log_prompt "${prompt_text}"
    read -r value </dev/tty
    if [[ -z "${value}" ]]; then
      echo -e "${RED}This field is required. Please enter a value.${NC}" >&2
    fi
  done

  echo "${value}"
}

# Prompt for an optional value (reads from /dev/tty to work in subshells)
prompt_optional() {
  local prompt_text="$1"
  local default="$2"

  log_prompt "${prompt_text} [default: ${default}]"
  read -r value </dev/tty
  if [[ -z "${value}" ]]; then
    echo "${default}"
  else
    echo "${value}"
  fi
}

# Main script
main() {
  echo ""
  echo "=========================================="
  echo "Affilibuster Production Environment Setup"
  echo "=========================================="
  echo ""

  # Check if .env.prod already exists
  if [[ -f ".env.prod" ]]; then
    log_warn ".env.prod already exists!"
    log_prompt "Overwrite? (y/N)"
    read -r confirm
    if [[ "${confirm}" != "y" && "${confirm}" != "Y" ]]; then
      echo "Aborted."
      exit 0
    fi
  fi

  log_info "Generating random secrets..."
  POSTGRES_PASSWORD=$(generate_password)
  ADMIN_JWT_SECRET=$(generate_secret)
  API_TOKEN_SALT=$(generate_secret)
  API_TOKEN_ENCRYPTION_KEY=$(generate_secret)
  TRANSFER_TOKEN_SALT=$(generate_secret)
  APP_KEYS=$(generate_secret)
  JWT_SECRET=$(generate_secret)
  REVALIDATE_SECRET=$(generate_secret)
  log_success "Secrets generated"

  echo ""
  echo "=========================================="
  echo "Cloudinary Configuration"
  echo "=========================================="
  echo "Get these values from: https://console.cloudinary.com/settings/api-keys"
  echo ""

  CLOUDINARY_NAME=$(prompt_required "Enter CLOUDINARY_NAME (Cloud name):" "CLOUDINARY_NAME")
  CLOUDINARY_KEY=$(prompt_required "Enter CLOUDINARY_KEY (API Key):" "CLOUDINARY_KEY")
  CLOUDINARY_SECRET=$(prompt_required "Enter CLOUDINARY_SECRET (API Secret):" "CLOUDINARY_SECRET")

  echo ""
  echo "=========================================="
  echo "Optional: Analytics Configuration"
  echo "=========================================="
  echo ""

  GA_ID=$(prompt_optional "Enter Google Analytics ID (GA4):" "")
  GTM_ID=$(prompt_optional "Enter Google Tag Manager ID:" "")

  log_info "Creating .env.prod..."

  cat >.env.prod <<EOF
# Copyright (c) 2026 Affilibuster by Ronen Druker.

# Affilibuster Environment Configuration - PRODUCTION (VPS)
# ==========================================================
# Generated by scripts/generate-env-prod.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# IMPORTANT: Never commit this file to version control!

# ======================================
# SHARED INFRASTRUCTURE
# ======================================

# PostgreSQL Database (internal Docker, no SSL needed)
POSTGRES_PROTOCOL=postgresql
POSTGRES_HOST=localhost
INTERNAL_POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_USER=affilibuster
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=affilibuster_db
POSTGRES_SSL=false
POSTGRES_SSL_REJECT_UNAUTHORIZED=true

# Redis Cache & Session Store (internal Docker)
REDIS_PROTOCOL=redis
REDIS_HOST=localhost
INTERNAL_REDIS_HOST=redis
REDIS_PORT=6379
REDIS_TTL_PREFERENCES=2592000

# ======================================
# CMS (Strapi 5 - Node.js)
# ======================================

# Server Configuration
CMS_PROTOCOL=https
CMS_PORT=443
CMS_HOST=cms.thegreenbrother.com
INTERNAL_CMS_HOST=strapi

# SSL paths not needed (Caddy handles SSL)
SSL_CERT_PATH=
SSL_KEY_PATH=

# CMS URLs
CMS_URL_PROD=https://cms.thegreenbrother.com
CMS_URL_DEV=https://cms.thegreenbrother.com

# Cloudinary
CLOUDINARY_NAME=${CLOUDINARY_NAME}
CLOUDINARY_KEY=${CLOUDINARY_KEY}
CLOUDINARY_SECRET=${CLOUDINARY_SECRET}

# Security Keys (auto-generated)
ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
API_TOKEN_SALT=${API_TOKEN_SALT}
API_TOKEN_ENCRYPTION_KEY=${API_TOKEN_ENCRYPTION_KEY}
TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
APP_KEYS=${APP_KEYS}

# ======================================
# BACKEND (FastAPI - Python 3.13)
# ======================================

# Application Configuration
APP_ENV=production
DEBUG=false
LOG_LEVEL=WARNING

# Server Configuration
BACKEND_PROTOCOL=https
BACKEND_PORT=8000
BACKEND_HOST=thegreenbrother.com
INTERNAL_BACKEND_HOST=backend

# Backend URLs
BACKEND_URL_PROD=https://thegreenbrother.com/api/v1
BACKEND_URL_DEV=https://thegreenbrother.com/api/v1

# Security (auto-generated)
JWT_SECRET=${JWT_SECRET}

# ======================================
# THE_GREEN_BROTHER (Next.js 16 - TypeScript)
# ======================================

# Environment
NODE_ENV=production
NEXT_TELEMETRY_DISABLED=1

# TheGreenBrother Configuration
THE_GREEN_BROTHER_PROTOCOL=https
THE_GREEN_BROTHER_PORT=3000
THE_GREEN_BROTHER_HOST=thegreenbrother.com
INTERNAL_THE_GREEN_BROTHER_HOST=the-green-brother

# Public URLs (browser-accessible via Caddy)
NEXT_PUBLIC_API_URL=https://thegreenbrother.com/api/v1
NEXT_PUBLIC_CMS_URL=https://cms.thegreenbrother.com

# Server-side API URL (internal Docker network)
NEXT_SERVER_SIDE_API_URL=http://backend:8000/v1

# Revalidation secret for ISR (auto-generated)
REVALIDATE_SECRET=${REVALIDATE_SECRET}

# Analytics
NEXT_PUBLIC_GA_ID=${GA_ID}
NEXT_PUBLIC_GTM_ID=${GTM_ID}
EOF

  log_success ".env.prod created successfully!"
  echo ""
  echo "=========================================="
  echo "Next Steps"
  echo "=========================================="
  echo ""
  echo "1. Review the generated file:"
  echo "   cat .env.prod"
  echo ""
  echo "2. Start production services:"
  echo "   docker compose -f docker-compose.prod.yaml up -d"
  echo ""
  echo "3. Check service health:"
  echo "   docker compose -f docker-compose.prod.yaml ps"
  echo ""
  log_warn "IMPORTANT: Keep .env.prod secure - it contains production secrets!"
  echo ""
}

main "$@"
