// Copyright (c) 2025 Affilibuster by Ronen Druker.

/**
 * Seed Data Loader from Strapi Export JSONL
 *
 * Loads test seed data from Strapi export files (data/entities/entities_00001.jsonl).
 * Uses JSONL format where each line is a JSON object with structure:
 * { type: "api::typename.typename", id: number, data: {...} }
 *
 * All data is typed using autogenerated types from OpenAPI specification.
 *
 * Usage:
 *   import { getSeedNavigation, getSeedFooter, getSeedProducts, getSeedCurrencies } from '../utils/seed-data'
 *
 *   const navData = getSeedNavigation(CodeEnum.EN)
 *   const products = getSeedProducts(CodeEnum.EN)
 *   const currencies = getSeedCurrencies()
 */

import type {
  ApiAboutAboutDocument,
  ApiContactContactDocument,
  ApiError404Error404Document,
  ApiError410Error410Document,
  ApiFooterFooterDocument,
  ApiHomepageHomepageDocument,
  ApiNavigationNavigationDocument,
  ApiPrivacyPrivacyDocument,
  ApiProductProductDocument,
  ApiSystemMessageSystemMessageDocument,
  ApiTermTermDocument,
  CodeEnum,
  Currency,
  Footer,
  Navigation,
} from '@/lib/generated/types.gen'
import { readFileSync } from 'fs'
import { join } from 'path'

/**
 * Entity record structure from Strapi export JSONL
 */
interface EntityRecord<T = unknown> {
  type: string
  id: number
  data: T
}

/**
 * Load and parse all entities from JSONL file
 */
function loadEntitiesFromJSONL(): EntityRecord[] {
  const entitiesPath = join(process.cwd(), 'data', 'entities', 'entities_00001.jsonl')
  const fileContent = readFileSync(entitiesPath, 'utf-8')

  const entities: EntityRecord[] = []
  for (const line of fileContent.split('\n')) {
    const trimmedLine = line.trim()
    if (!trimmedLine) continue // Skip empty lines

    try {
      const parsed = JSON.parse(trimmedLine) as EntityRecord
      entities.push(parsed)
    } catch (error) {
      console.error(`Failed to parse JSONL line: ${trimmedLine.substring(0, 50)}...`, error)
    }
  }

  return entities
}

// Cache loaded entities for performance
const CACHED_ENTITIES = loadEntitiesFromJSONL()

/**
 * Get all entities of a specific type
 */
function getEntitiesByType<T>(type: string): T[] {
  return CACHED_ENTITIES.filter(entity => entity.type === type).map(entity => entity.data as T)
}

/**
 * Get entities filtered by type and locale
 */
function getEntitiesByTypeAndLocale<T extends { locale?: string }>(type: string, locale: CodeEnum): T[] {
  return getEntitiesByType<T>(type).filter(entity => entity.locale === locale)
}

/**
 * Strip CMS metadata fields from document to match expected type
 */
function stripMetadata<T extends Record<string, unknown>>(
  doc: T
): Omit<
  T,
  'documentId' | 'id' | 'createdAt' | 'updatedAt' | 'publishedAt' | 'locale' | 'localizations' | 'entryTitle'
> {
  const {
    documentId: _documentId,
    id: _id,
    createdAt: _createdAt,
    updatedAt: _updatedAt,
    publishedAt: _publishedAt,
    locale: _locale,
    localizations: _localizations,
    entryTitle: _entryTitle,
    ...rest
  } = doc
  return rest
}

/**
 * Get Navigation data for a specific locale
 * @param locale - The locale to get navigation data for
 * @returns Strongly-typed Navigation object
 */
export function getSeedNavigation(locale: CodeEnum): Navigation {
  const docs = getEntitiesByTypeAndLocale<ApiNavigationNavigationDocument>('api::navigation.navigation', locale)

  if (docs.length === 0) {
    throw new Error(`No navigation data found for locale: ${locale}`)
  }

  const doc = docs[0]
  if (!doc) {
    throw new Error(`No navigation data found for locale: ${locale}`)
  }

  return stripMetadata(doc) as Navigation
}

/**
 * Get Footer data for a specific locale
 * @param locale - The locale to get footer data for
 * @returns Strongly-typed Footer object
 */
export function getSeedFooter(locale: CodeEnum): Footer {
  const docs = getEntitiesByTypeAndLocale<ApiFooterFooterDocument>('api::footer.footer', locale)

  if (docs.length === 0) {
    throw new Error(`No footer data found for locale: ${locale}`)
  }

  const doc = docs[0]
  if (!doc) {
    throw new Error(`No footer data found for locale: ${locale}`)
  }

  return stripMetadata(doc) as Footer
}

/**
 * Get all currencies from seed data
 * @returns Array of strongly-typed Currency objects
 */
export function getSeedCurrencies(): Currency[] {
  // Currency has no locale field, so we load all
  return getEntitiesByType<Currency>('api::currency.currency')
}

/**
 * Get Products for a specific locale
 * @param locale - The locale to get products for
 * @returns Array of strongly-typed Product objects (documents)
 */
export function getSeedProducts(locale: CodeEnum): ApiProductProductDocument[] {
  return getEntitiesByTypeAndLocale<ApiProductProductDocument>('api::product.product', locale)
}

/**
 * Get Homepage data for a specific locale
 * @param locale - The locale to get homepage data for
 * @returns Homepage data object
 */
export function getSeedHomepage(locale: CodeEnum): ApiHomepageHomepageDocument {
  const docs = getEntitiesByTypeAndLocale<ApiHomepageHomepageDocument>('api::homepage.homepage', locale)

  if (docs.length === 0) {
    throw new Error(`No homepage data found for locale: ${locale}`)
  }

  const doc = docs[0]
  if (!doc) {
    throw new Error(`No homepage data found for locale: ${locale}`)
  }

  return doc
}

/**
 * Get About page data for a specific locale
 * @param locale - The locale to get about data for
 * @returns About page data object
 */
export function getSeedAbout(locale: CodeEnum): ApiAboutAboutDocument {
  const docs = getEntitiesByTypeAndLocale<ApiAboutAboutDocument>('api::about.about', locale)

  if (docs.length === 0) {
    throw new Error(`No about data found for locale: ${locale}`)
  }

  const doc = docs[0]
  if (!doc) {
    throw new Error(`No about data found for locale: ${locale}`)
  }

  return doc
}

/**
 * Get Contact page data for a specific locale
 * @param locale - The locale to get contact data for
 * @returns Contact page data object
 */
export function getSeedContact(locale: CodeEnum): ApiContactContactDocument {
  const docs = getEntitiesByTypeAndLocale<ApiContactContactDocument>('api::contact-us.contact-us', locale)

  if (docs.length === 0) {
    throw new Error(`No contact data found for locale: ${locale}`)
  }

  const doc = docs[0]
  if (!doc) {
    throw new Error(`No contact data found for locale: ${locale}`)
  }

  return doc
}

/**
 * Get Privacy page data for a specific locale
 * @param locale - The locale to get privacy data for
 * @returns Privacy page data object
 */
export function getSeedPrivacy(locale: CodeEnum): ApiPrivacyPrivacyDocument {
  const docs = getEntitiesByTypeAndLocale<ApiPrivacyPrivacyDocument>('api::privacy.privacy', locale)

  if (docs.length === 0) {
    throw new Error(`No privacy data found for locale: ${locale}`)
  }

  const doc = docs[0]
  if (!doc) {
    throw new Error(`No privacy data found for locale: ${locale}`)
  }

  return doc
}

/**
 * Get Terms page data for a specific locale
 * @param locale - The locale to get terms data for
 * @returns Terms page data object
 */
export function getSeedTerms(locale: CodeEnum): ApiTermTermDocument {
  const docs = getEntitiesByTypeAndLocale<ApiTermTermDocument>('api::term.term', locale)

  if (docs.length === 0) {
    throw new Error(`No terms data found for locale: ${locale}`)
  }

  const doc = docs[0]
  if (!doc) {
    throw new Error(`No terms data found for locale: ${locale}`)
  }

  return doc
}

/**
 * Get Error 404 page data for a specific locale
 * @param locale - The locale to get error 404 data for
 * @returns Error 404 page data object
 */
export function getSeedError404(locale: CodeEnum): ApiError404Error404Document {
  const docs = getEntitiesByTypeAndLocale<ApiError404Error404Document>('api::error-404.error-404', locale)

  if (docs.length === 0) {
    throw new Error(`No error 404 data found for locale: ${locale}`)
  }

  const doc = docs[0]
  if (!doc) {
    throw new Error(`No error 404 data found for locale: ${locale}`)
  }

  return doc
}

/**
 * Get Error 410 page data for a specific locale
 * @param locale - The locale to get error 410 data for
 * @returns Error 410 page data object
 */
export function getSeedError410(locale: CodeEnum): ApiError410Error410Document {
  const docs = getEntitiesByTypeAndLocale<ApiError410Error410Document>('api::error-410.error-410', locale)

  if (docs.length === 0) {
    throw new Error(`No error 410 data found for locale: ${locale}`)
  }

  const doc = docs[0]
  if (!doc) {
    throw new Error(`No error 410 data found for locale: ${locale}`)
  }

  return doc
}

/**
 * Get System Message data for a specific locale
 * @param locale - The locale to get system message data for
 * @returns System message data object
 */
export function getSeedSystemMessage(locale: CodeEnum): ApiSystemMessageSystemMessageDocument {
  const docs = getEntitiesByTypeAndLocale<ApiSystemMessageSystemMessageDocument>(
    'api::system-message.system-message',
    locale
  )

  if (docs.length === 0) {
    throw new Error(`No system message data found for locale: ${locale}`)
  }

  const doc = docs[0]
  if (!doc) {
    throw new Error(`No system message data found for locale: ${locale}`)
  }

  return doc
}

/**
 * Get a specific currency by code
 * @param code - The currency code
 * @returns Strongly-typed Currency object or undefined
 */
export function getSeedCurrency(code: string): Currency | undefined {
  const currencies = getSeedCurrencies()
  return currencies.find(c => c.code === code)
}

/**
 * Get a specific product by slug
 * @param locale - The locale to search in
 * @param slug - The product slug
 * @returns Strongly-typed Product object or undefined
 */
export function getSeedProduct(locale: CodeEnum, slug: string): ApiProductProductDocument | undefined {
  const products = getSeedProducts(locale)
  return products.find(p => p.slug === slug)
}
